/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaproject;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import org.jxmapviewer.JXMapViewer;
import org.jxmapviewer.OSMTileFactoryInfo;
import org.jxmapviewer.viewer.DefaultTileFactory;
import org.jxmapviewer.viewer.GeoPosition;


/**
 *
 * @author megas
 */
public class LossPollus extends javax.swing.JFrame {
     private int FriedCCount;
    private int ChickWCount;
private int FFCount;


 private Connection con;
    private final String dbUrl = "jdbc:oracle:thin:@localhost:1521:xe"; // Your database URL
    private final String dbUser = "system"; // Database username
    private final String dbPassword = "karmegam"; // Database password
    private String username;
    private int memberId;

    /**
     * Creates new form LossPollus
     */
    public LossPollus() {
        initComponents();
        FriedCCount = 0;
    ChickWCount = 0;
    FFCount = 0;
    jLabel4.setText(Integer.toString(FriedCCount));
    jLabel7.setText(Integer.toString(ChickWCount));
    jLabel9.setText(Integer.toString(FFCount));
         
        try {
            con = DriverManager.getConnection(dbUrl, dbUser, dbPassword);
            System.out.println("Connected to the database.");
        } catch (SQLException e) {
            System.out.println("Connection failed. Error: " + e.getMessage());
        }
        initMap();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CartButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        FDecButton = new javax.swing.JButton();
        FIncButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        CDecButton = new javax.swing.JButton();
        CIncButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        FFDecButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        FFIncButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\javaproject4\\LP.jpg")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel2.setText("                         LOSS POLLUS HERMANUS");

        CartButton.setBackground(new java.awt.Color(153, 255, 255));
        CartButton.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        CartButton.setText("CART");
        CartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CartButtonActionPerformed(evt);
            }
        });

        BackButton.setBackground(new java.awt.Color(153, 255, 255));
        BackButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BackButton.setText("<<");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(102, 102, 0));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel3.setText("BEST SELLER");

        FDecButton.setBackground(new java.awt.Color(153, 255, 255));
        FDecButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FDecButton.setText("-");
        FDecButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FDecButtonActionPerformed(evt);
            }
        });

        FIncButton.setBackground(new java.awt.Color(153, 255, 255));
        FIncButton.setText("+");
        FIncButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FIncButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel5.setText("FRIED CHICKEN");

        jLabel12.setText("RS.180");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FDecButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(FIncButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(FDecButton)
                        .addComponent(jLabel5))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(FIncButton))
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setIcon(new javax.swing.ImageIcon("E:\\javaproject4\\chickw.jpg")); // NOI18N

        CDecButton.setBackground(new java.awt.Color(204, 255, 255));
        CDecButton.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        CDecButton.setText("-");
        CDecButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CDecButtonActionPerformed(evt);
            }
        });

        CIncButton.setBackground(new java.awt.Color(204, 255, 255));
        CIncButton.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        CIncButton.setText("+");
        CIncButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CIncButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("jLabel7");

        jLabel8.setIcon(new javax.swing.ImageIcon("E:\\javaproject4\\frenf.jpg")); // NOI18N

        FFDecButton.setBackground(new java.awt.Color(204, 255, 255));
        FFDecButton.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        FFDecButton.setText("-");
        FFDecButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FFDecButtonActionPerformed(evt);
            }
        });

        jLabel9.setText("jLabel9");

        FFIncButton.setBackground(new java.awt.Color(204, 255, 255));
        FFIncButton.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        FFIncButton.setText("+");
        FFIncButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FFIncButtonActionPerformed(evt);
            }
        });

        jLabel10.setText("Chicken wings  RS.200");

        jLabel11.setText("French Fries      RS.100");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(14, 14, 14)))))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CDecButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FFDecButton, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CIncButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FFIncButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CIncButton)
                    .addComponent(CDecButton)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(67, 67, 67)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(FFDecButton)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(FFIncButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 557, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 762, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 359, Short.MAX_VALUE)
                .addComponent(CartButton)
                .addGap(32, 32, 32))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CartButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BackButton)
                        .addGap(63, 63, 63)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void initMap() {
    // Create a JXMapViewer instance
    JXMapViewer mapViewer = new JXMapViewer();

    // Set the tile factory
    OSMTileFactoryInfo info = new OSMTileFactoryInfo();
    DefaultTileFactory tileFactory = new DefaultTileFactory(info);
    mapViewer.setTileFactory(tileFactory);

    // Set the focus to the specified location (Madurai Mess)
    GeoPosition losspollusLocation = new GeoPosition(9.919972590799059, 78.0938435327464); // Example coordinates for Madurai Mess
    mapViewer.setZoom(3); // Increased zoom level
    mapViewer.setAddressLocation(losspollusLocation);

    // Set preferred size for the map viewer
    mapViewer.setPreferredSize(new Dimension(600, 400));

    // Add the map to jPanel8
    jPanel5.setLayout(new BorderLayout());
    jPanel5.add(mapViewer, BorderLayout.CENTER);
}

    private void CDecButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CDecButtonActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        if (ChickWCount > 0) {
        ChickWCount--;
        // Update the dosa count label
        jLabel7.setText(Integer.toString(ChickWCount));
        // Remove the dosa from the cart when - button is clicked
        removeFromCart("Chicken Wings");
    } else {
        // Display a warning message if the dosa count is already 0
        JOptionPane.showMessageDialog(this, "Chicken Wings count is already 0", "Warning", JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_CDecButtonActionPerformed

    private void FIncButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FIncButtonActionPerformed
        // TODO add your handling code here:
        FriedCCount++;
        // Update the dosa count label
        jLabel4.setText(Integer.toString(FriedCCount));
       addToCart(1,"Fried Chicken", FriedCCount);
    }//GEN-LAST:event_FIncButtonActionPerformed

    private void FDecButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FDecButtonActionPerformed
        // TODO add your handling code here:
         if (FriedCCount > 0) {
        FriedCCount--;
        // Update the dosa count label
        jLabel4.setText(Integer.toString(FriedCCount));
        // Remove the dosa from the cart when - button is clicked
        removeFromCart("Fried Chicken");
    } else {
        // Display a warning message if the dosa count is already 0
        JOptionPane.showMessageDialog(this, "Fried Chicken count is already 0", "Warning", JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_FDecButtonActionPerformed

    private void CIncButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CIncButtonActionPerformed
        // TODO add your handling code here:
         ChickWCount++;
        // Update the dosa count label
        jLabel7.setText(Integer.toString(ChickWCount));
       addToCart(1,"Chicken Wings", ChickWCount);
    }//GEN-LAST:event_CIncButtonActionPerformed

    private void FFIncButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FFIncButtonActionPerformed
        // TODO add your handling code here:
          FFCount++;
        // Update the dosa count label
        jLabel9.setText(Integer.toString(FFCount));
       addToCart(1,"French Fries", FFCount);
    }//GEN-LAST:event_FFIncButtonActionPerformed

    private void FFDecButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FFDecButtonActionPerformed
        // TODO add your handling code here:
        if (FFCount > 0) {
        FFCount--;
        // Update the dosa count label
        jLabel9.setText(Integer.toString(FFCount));
        // Remove the dosa from the cart when - button is clicked
        removeFromCart("Fried Chicken");
    } else {
        // Display a warning message if the dosa count is already 0
        JOptionPane.showMessageDialog(this, "French Fries count is already 0", "Warning", JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_FFDecButtonActionPerformed

    private void CartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CartButtonActionPerformed
        // TODO add your handling code here:
         CartManager c = new CartManager();
    
    // Display the cart contents
    c.displayCartContents();
    
    // Make the CartManager window visible
    c.setVisible(true);
    }//GEN-LAST:event_CartButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        MemberFrame memberFrame = new MemberFrame();
        memberFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_BackButtonActionPerformed
private void addToCart(int memberId, String itemName, int count) {
    try {
        // Fetch the item_id from the menu_items table based on itemName
        int itemId = getItemIdByName(itemName);
          memberId = getMemberId("mega"); 

        
        // Fetch the last cartId from the cart table
        int cartId = getLastCartId();
        
        String insertQuery = "INSERT INTO cart (cart_id, member_id, item_id, quantity) VALUES (?, ?, ?, ?)";
        PreparedStatement insertStatement = con.prepareStatement(insertQuery);
        insertStatement.setInt(1, cartId);
        insertStatement.setInt(2, memberId);
        insertStatement.setInt(3, itemId);
        insertStatement.setInt(4, count);
        insertStatement.executeUpdate();

        JOptionPane.showMessageDialog(null, "Item added to cart successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error adding item to cart: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
    }
}



private int getLastCartId() throws SQLException {
    int lastCartId = 0;
    String query = "SELECT MAX(cid) AS last_cart_id FROM cart";
    try (PreparedStatement statement = con.prepareStatement(query);
         ResultSet resultSet = statement.executeQuery()) {
        if (resultSet.next()) {
            lastCartId = resultSet.getInt("last_cart_id");
        }
    }
    return lastCartId;
}

private int getLastItemId() throws SQLException {
    int lastItemId = 0;
    String query = "SELECT item_id AS last_item_id\n" +
"FROM cart\n" +
"WHERE quantity = (SELECT MAX(quantity) FROM cart)";
    try (PreparedStatement statement = con.prepareStatement(query);
         ResultSet resultSet = statement.executeQuery()) {
        if (resultSet.next()) {
            lastItemId = resultSet.getInt("last_item_id");
        }
    }
    return lastItemId;
}


  private int getMemberId(String username) throws SQLException {
        int memberId = -1;
        String query = "SELECT id FROM members WHERE username = ?";
        try (PreparedStatement statement = con.prepareStatement(query)) {
            statement.setString(1, username);
            try (ResultSet resultSet = statement.executeQuery()) {
                if (resultSet.next()) {
                    memberId = resultSet.getInt("id");
                }
            }
        }
        return memberId;
    }

 private void removeFromCart(String itemName) {
    try {
        // Get the member ID
        int memberId = getMemberId(username); 
        
        // Get the item ID
        int itemId = getItemIdByName(itemName);
        int lastItemId = getLastItemId();
        // Get the last cart ID
        int cartId = getLastCartId();

        // Prepare the SQL statement to decrement the quantity
        String sql = "UPDATE cart SET quantity = quantity - 1 WHERE item_id = ? AND quantity > 0";
        PreparedStatement pstmt = con.prepareStatement(sql);
        pstmt.setInt(1, itemId);  // Set last item_id
        
        // Execute the update
        int rowsUpdated = pstmt.executeUpdate();

        // Check if any rows were updated
        if (rowsUpdated > 0) {
            JOptionPane.showMessageDialog(null, "Item removed from cart successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Item not found in cart or quantity already 0", "Warning", JOptionPane.WARNING_MESSAGE);
        }

        // Close the PreparedStatement
        pstmt.close();
    } catch (SQLException e) {
        e.printStackTrace();
    }
}




    private int getItemIdByName(String itemName) {
        int itemId = 0;
        try {
            String sql = "SELECT item_id FROM menu_items WHERE item_name = ?";
            PreparedStatement pstmt = con.prepareStatement(sql);
            pstmt.setString(1, itemName);
            ResultSet rs = pstmt.executeQuery();
            if (rs.next()) {
                itemId = rs.getInt("item_id");
            }
            rs.close();
            pstmt.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return itemId;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LossPollus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LossPollus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LossPollus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LossPollus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LossPollus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton CDecButton;
    private javax.swing.JButton CIncButton;
    private javax.swing.JButton CartButton;
    private javax.swing.JButton FDecButton;
    private javax.swing.JButton FFDecButton;
    private javax.swing.JButton FFIncButton;
    private javax.swing.JButton FIncButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
